export const mangleKeyMap: Record<string, string> = {
  accel: 'a',
  aero: 'b',
  aeroAndAppearance: 'c',
  aspiration: 'd',
  balance: 'e',
  bias: 'f',
  bodyKit: 'g',
  brake: 'h',
  brakes: 'i',
  build: 'j',
  bump: 'k',
  camber: 'l',
  camshaft: 'm',
  carburator: 'n',
  caster: 'o',
  center: 'p',
  centrifugalSupercharger: 'q',
  chassisReinforcement: 'r',
  classification: 's',
  clutch: 't',
  compound: 'u',
  conversions: 'v',
  damping: 'w',
  decel: 'x',
  diff: 'y',
  differential: 'z',
  displacement: 'aa',
  driveline: 'ab',
  drivetrain: 'ac',
  engine: 'ad',
  exhaust: 'ae',
  flywheel: 'af',
  front: 'ag',
  frontArb: 'ah',
  frontBumper: 'ai',
  fuelSystem: 'aj',
  gears: 'ak',
  hood: 'al',
  hp: 'am',
  ignition: 'an',
  intake: 'ao',
  intakeManifold: 'ap',
  intercooler: 'aq',
  length: 'ar',
  make: 'as',
  model: 'at',
  na: 'au',
  name: 'av',
  none: 'aw',
  oilCooling: 'ax',
  pi: 'ay',
  pistons: 'az',
  platformAndHandling: 'ba',
  pressure: 'bb',
  ratios: 'bc',
  rear: 'bd',
  rearArb: 'be',
  rearBumper: 'bf',
  rearWing: 'bg',
  removed: 'bh',
  rideHeight: 'bi',
  rimSize: 'bj',
  rimStyle: 'bk',
  shareCode: 'bl',
  sideSkirts: 'bm',
  springs: 'bn',
  stats: 'bo',
  supercharger: 'bp',
  tires: 'bq',
  tiresAndRims: 'br',
  topSpeed: 'bs',
  torque: 'bt',
  trackWidth: 'bu',
  transmission: 'bv',
  tune: 'bw',
  turbo: 'bx',
  twinTurbo: 'by',
  type: 'bz',
  units: 'ca',
  valves: 'cb',
  weight: 'cc',
  weightReduction: 'cd',
  width: 'ce',
  zeroToHundred: 'cf',
  zeroToSixty: 'cg',
};

export const mangleValueMap: Record<string, string> = {
  Stock: 's',
  Street: 'st',
  Sport: 'sp',
  'Semi-Slick': 'ss',
  Race: 'r',
  Slick: 'sl',
  Drift: 'dr',
  Rally: 'ra',
  Offroad: 'o',
  Snow: 'sn',
  Drag: 'd',
  'Vintage Whitewall': 'vw',
  'Vintage Race': 'vr',
  'Multi Piece': 'mp',
  Specialized: 'spec',
  First: '1st',
  Second: '2nd',
  Third: '3rd',
  'Remove Restrictor': 'rr',
  'No Restrictor Plate': 'nrp',
  'Stock Restrictor Plate': 'srp',
  'N/A': 'na',
};
