import makes from './makes';

interface BaseCarModel {
  year: number;
  make: string;
  model: string;
}

interface CarModel extends BaseCarModel {
  fullname: string;
  shortname: string;
}

const models: BaseCarModel[] = [
  { year: 2017, make: 'Abarth', model: '124 Spider' },
  { year: 1968, make: 'Abarth', model: '595 esseesse' },
  { year: 2016, make: 'Abarth', model: '695 Biposto' },
  { year: 1980, make: 'Abarth', model: 'Fiat 131' },
  { year: 2001, make: 'Acura', model: 'Integra Type-R' },
  { year: 2002, make: 'Acura', model: 'RSX Type-S' },
  { year: 1992, make: 'Alfa Romeo', model: '155 Q4' },
  { year: 1968, make: 'Alfa Romeo', model: '33 Stradale' },
  { year: 2014, make: 'Alfa Romeo', model: '4C' },
  { year: 2007, make: 'Alfa Romeo', model: '8C Competizione' },
  { year: 2007, make: 'Alfa Romeo', model: '8C Competizione Forza Edition' },
  { year: 2017, make: 'Alfa Romeo', model: 'Giulia Quadrifoglio' },
  { year: 2017, make: 'Alfa Romeo', model: 'Giulia Quadrifoglio Forza Edition' },
  { year: 1965, make: 'Alfa Romeo', model: 'Giulia Sprint GTA Stradale' },
  { year: 1965, make: 'Alfa Romeo', model: 'Giulia TZ2' },
  { year: 1934, make: 'Alfa Romeo', model: 'P3' },
  { year: 2018, make: 'Alfa Romeo', model: 'Stelvio Quadrifoglio' },
  { year: 2017, make: 'Alpine', model: 'A110' },
  { year: 2015, make: 'Alumi Craft', model: 'Class 10 Race Car' },
  { year: 2015, make: 'Alumi Craft', model: 'Class 10 Race Car Forza Edition' },
  { year: 1973, make: 'AMC', model: 'Gremlin X' },
  { year: 1972, make: 'AMC', model: 'Javelin AMX' },
  { year: 1970, make: 'AMC', model: 'Rebel \"The Machine\"' },
  { year: 2554, make: 'AMG', model: 'Transport Dynamics M12S Warthog CST' },
  { year: 2018, make: 'Apollo', model: 'Intensa Emozione' },
  { year: 2013, make: 'Ariel', model: 'Atom 500 V8' },
  { year: 2016, make: 'Ariel', model: 'Nomad' },
  { year: 2012, make: 'Ascari', model: 'KZ1R' },
  { year: 1960, make: 'Aston Martin', model: 'DB4 GT Zagato' },
  { year: 1964, make: 'Aston Martin', model: 'DB5' },
  { year: 1958, make: 'Aston Martin', model: 'DBR1' },
  { year: 2019, make: 'Aston Martin', model: 'DBS Superleggera' },
  { year: 2013, make: 'Aston Martin', model: 'V12 Vantage S' },
  { year: 2017, make: 'Aston Martin', model: 'Vanquish Zagato Coupé' },
  { year: 2018, make: 'Aston Martin', model: 'Vantage' },
  { year: 2016, make: 'Aston Martin', model: 'Vantage GT12' },
  { year: 2016, make: 'Aston Martin', model: 'Vulcan AMR Pro' },
  { year: 2018, make: 'ATS', model: 'GT' },
  { year: 2013, make: 'Audi', model: 'R8 Coupé V10 plus 5.2 FSI quattro' },
  { year: 2016, make: 'Audi', model: 'R8 V10 plus' },
  { year: 1995, make: 'Audi', model: 'RS 2 Avant' },
  { year: 2011, make: 'Audi', model: 'RS 3 Sportback' },
  { year: 2001, make: 'Audi', model: 'RS 4 Avant' },
  { year: 2013, make: 'Audi', model: 'RS 4 Avant' },
  { year: 2011, make: 'Audi', model: 'RS 5 Coupé' },
  { year: 2003, make: 'Audi', model: 'RS 6' },
  { year: 2015, make: 'Audi', model: 'RS 6 Avant' },
  { year: 2013, make: 'Audi', model: 'RS 7 Sportback' },
  { year: 2015, make: 'Audi', model: 'S1' },
  { year: 2010, make: 'Audi', model: 'TT RS Coupé' },
  { year: 2015, make: 'Audi', model: 'TTS Coupé' },
  { year: 1964, make: 'Austin', model: 'FX4 Taxi' },
  { year: 1964, make: 'Austin', model: 'FX4 (Horizon Story)' },
  { year: 1924, make: 'Austin', model: 'Seven' },
  { year: 1965, make: 'Austin Healey', model: '3000 MkIII' },
  { year: 1958, make: 'Austin Healey', model: 'Sprite MkI' },
  { year: 2014, make: 'BAC', model: 'Mono' },
  { year: 1931, make: 'Bentley', model: '4-1/2 Liter Supercharged' },
  { year: 1931, make: 'Bentley', model: '8-Liter' },
  { year: 1991, make: 'Bentley', model: 'Turbo R' },
  { year: 2011, make: 'BMW', model: '1 Series M Coupé' },
  { year: 1973, make: 'BMW', model: '2002 Turbo' },
  { year: 2015, make: 'BMW', model: 'i8' },
  { year: 2018, make: 'BMW', model: 'i8 Roadster' },
  { year: 1957, make: 'BMW', model: 'Isetta 300 Export' },
  { year: 1981, make: 'BMW', model: 'M1' },
  { year: 2016, make: 'BMW', model: 'M2 Coupé' },
  { year: 1991, make: 'BMW', model: 'M3' },
  { year: 1997, make: 'BMW', model: 'M3' },
  { year: 2005, make: 'BMW', model: 'M3' },
  { year: 2008, make: 'BMW', model: 'M3' },
  { year: 2010, make: 'BMW', model: 'M3 GTS' },
  { year: 2002, make: 'BMW', model: 'M3-GTR' },
  { year: 2014, make: 'BMW', model: 'M4 Coupé' },
  { year: 2016, make: 'BMW', model: 'M4 GTS' },
  { year: 1988, make: 'BMW', model: 'M5' },
  { year: 1988, make: 'BMW', model: 'M5 Forza Edition' },
  { year: 1995, make: 'BMW', model: 'M5' },
  { year: 2003, make: 'BMW', model: 'M5' },
  { year: 2009, make: 'BMW', model: 'M5' },
  { year: 2012, make: 'BMW', model: 'M5' },
  { year: 2018, make: 'BMW', model: 'M5' },
  { year: 2013, make: 'BMW', model: 'M6 Coupe' },
  { year: 2013, make: 'BMW', model: 'M6 Coupe Forza Edition' },
  { year: 2011, make: 'BMW', model: 'X5 M' },
  { year: 2015, make: 'BMW', model: 'X6 M' },
  { year: 2002, make: 'BMW', model: 'Z3 M Coupe' },
  { year: 2008, make: 'BMW', model: 'Z4 M Coupe' },
  { year: 2018, make: 'BMW', model: 'Z4 Roadster' },
  { year: 2011, make: 'BMW', model: 'Z4 sDrive35is' },
  { year: 2012, make: 'Bowler', model: 'EXR S' },
  { year: 1992, make: 'Bugatti', model: 'EB110 Super Sport' },
  { year: 1926, make: 'Bugatti', model: 'Type 35 C' },
  { year: 1970, make: 'Buick', model: 'GSX' },
  { year: 1987, make: 'Buick', model: 'Regal GNX' },
  { year: 2016, make: 'Cadillac', model: 'CTS-V Sedan' },
  { year: 1959, make: 'Cadillac', model: 'Eldorado Biarritz Convertible' },
  { year: 2012, make: 'Cadillac', model: 'Escalade ESV' },
  { year: 2013, make: 'Cadillac', model: 'XTS Limousine' },
  { year: 2018, make: 'Can Am', model: 'Maverick X RS Turbo R' },
  { year: 2013, make: 'Caterham', model: 'Superlight R500' },
  { year: 2013, make: 'Caterham', model: 'Superlight R500 Forza Edition' },
  { year: 1955, make: 'Chevrolet', model: '150 Utility Sedan' },
  { year: 1957, make: 'Chevrolet', model: 'Bel Air' },
  { year: 1957, make: 'Chevrolet', model: 'Bel Air (Horizon Story)' },
  { year: 1990, make: 'Chevrolet', model: 'Camaro IROC-Z' },
  { year: 1969, make: 'Chevrolet', model: 'Camaro Super Sport Coupe' },
  { year: 2015, make: 'Chevrolet', model: 'Camaro Z/28' },
  { year: 1970, make: 'Chevrolet', model: 'Camaro Z28' },
  { year: 2017, make: 'Chevrolet', model: 'Camaro ZL1' },
  { year: 2017, make: 'Chevrolet', model: 'Camaro ZL1 Preorder Car' },
  { year: 2018, make: 'Chevrolet', model: 'Camaro ZL1 1LE' },
  { year: 1967, make: 'Chevrolet', model: 'Chevelle Super Sport 396' },
  { year: 1970, make: 'Chevrolet', model: 'Chevelle Super Sport 454' },
  { year: 1970, make: 'Chevrolet', model: 'Chevelle Super Sport Barrett-Jackson Edition' },
  { year: 2017, make: 'Chevrolet', model: 'Colorado ZR2' },
  { year: 1953, make: 'Chevrolet', model: 'Corvette' },
  { year: 1967, make: 'Chevrolet', model: 'Corvette Stingray 427' },
  { year: 2020, make: 'Chevrolet', model: 'Corvette Stingray Coupe' },
  { year: 2002, make: 'Chevrolet', model: 'Corvette Z06' },
  { year: 1970, make: 'Chevrolet', model: 'Corvette ZR-1' },
  { year: 1995, make: 'Chevrolet', model: 'Corvette ZR-1' },
  { year: 2009, make: 'Chevrolet', model: 'Corvette ZR1' },
  { year: 2019, make: 'Chevrolet', model: 'Corvette ZR1' },
  { year: 1970, make: 'Chevrolet', model: 'El Camino Super Sport 454' },
  { year: 1988, make: 'Chevrolet', model: 'El Camino Super Sport 454' },
  { year: 1996, make: 'Chevrolet', model: 'Impala Super Sport' },
  { year: 1964, make: 'Chevrolet', model: 'Impala Super Sport 409' },
  { year: 1988, make: 'Chevrolet', model: 'Monte Carlo Super Sport' },
  { year: 1966, make: 'Chevrolet', model: 'Nova Super Sport' },
  { year: 1969, make: 'Chevrolet', model: 'Nova Super Sport 396' },
  { year: 1969, make: 'Chevrolet', model: 'Nova Super Sport 396 Forza Edition' },
  { year: 1972, make: 'Chrysler', model: 'VH Valiant Charger R/T E49' },
  { year: 1975, make: 'Citroën', model: 'DS 23' },
  { year: 1970, make: 'Datsun', model: '510' },
  { year: 1970, make: 'Dodge', model: 'Challenger R/T' },
  { year: 1969, make: 'Dodge', model: 'Charger Daytona Hemi' },
  { year: 1969, make: 'Dodge', model: 'Charger R/T' },
  { year: 1968, make: 'Dodge', model: 'Dart Hemi Super Stock' },
  { year: 2018, make: 'Dodge', model: 'Durango SRT' },
  { year: 2016, make: 'Dodge', model: 'Viper ACR' },
  { year: 2008, make: 'Dodge', model: 'Viper SRT10 ACR' },
  { year: 2013, make: 'Donkervoort', model: 'D8 GTO' },
  { year: 2011, make: 'DS', model: 'Automobiles DS3 Racing' },
  { year: 2018, make: 'Exomotive', model: 'Exocet Off-Road' },
  { year: 1973, make: 'Ferrari', model: '166MM Barchetta' },
  { year: 1957, make: 'Ferrari', model: '250 California' },
  { year: 1962, make: 'Ferrari', model: '250 GT Berlinetta Lusso' },
  { year: 1962, make: 'Ferrari', model: '250 GTO' },
  { year: 1962, make: 'Ferrari', model: '250LM' },
  { year: 1962, make: 'Ferrari', model: '250 Testa Rossa' },
  { year: 1984, make: 'Ferrari', model: '288 GTO' },
  { year: 2003, make: 'Ferrari', model: '360 Challenge Stradale' },
  { year: 1968, make: 'Ferrari', model: '365 GTB/4' },
  { year: 2007, make: 'Ferrari', model: '430 Scuderia' },
  { year: 2013, make: 'Ferrari', model: '458 Speciale' },
  { year: 2018, make: 'Ferrari', model: '488 Pista' },
  { year: 1953, make: 'Ferrari', model: '500 Mondial' },
  { year: 1970, make: 'Ferrari', model: '512 S' },
  { year: 1992, make: 'Ferrari', model: '512 TR' },
  { year: 2002, make: 'Ferrari', model: '575M Maranello' },
  { year: 2012, make: 'Ferrari', model: '599XX Evolution' },
  { year: 2017, make: 'Ferrari', model: '812 Superfast' },
  { year: 2014, make: 'Ferrari', model: 'California T' },
  { year: 1969, make: 'Ferrari', model: 'Dino 246 GT' },
  { year: 2002, make: 'Ferrari', model: 'Enzo Ferrari' },
  { year: 2011, make: 'Ferrari', model: 'FF' },
  { year: 1987, make: 'Ferrari', model: 'F40' },
  { year: 1989, make: 'Ferrari', model: 'F40 Competizione' },
  { year: 1995, make: 'Ferrari', model: 'F50' },
  { year: 1994, make: 'Ferrari', model: 'F355 Berlinetta' },
  { year: 2005, make: 'Ferrari', model: 'FXX' },
  { year: 2017, make: 'Ferrari', model: 'GTC4Lusso' },
  { year: 2018, make: 'Ferrari', model: 'Portofino' },
  { year: 1980, make: 'FIAT', model: '124 Sport Spider' },
  { year: 1969, make: 'FIAT', model: 'Dino 2.4 Coupe' },
  { year: 1975, make: 'FIAT', model: 'X1/9' },
  { year: 1977, make: 'Ford', model: '#5 Escort RS1800 MK II' },
  { year: 2018, make: 'Ford', model: '#25 Mustang RTR' },
  { year: 2018, make: 'Ford', model: '#88 Mustang RTR' },
  { year: 2017, make: 'Ford', model: '#14 Rahal Letterman Lanigan Racing GRC Fiesta' },
  { year: 1959, make: 'Ford', model: 'Anglia 105E' },
  { year: 1973, make: 'Ford', model: 'Bronco' },
  { year: 1975, make: 'Ford', model: 'Bronco Barrett-Jackson Edition' },
  { year: 1973, make: 'Ford', model: 'Capri RS3100' },
  { year: 2010, make: 'Ford', model: 'Crown Victoria Police Interceptor' },
  { year: 1940, make: 'Ford', model: 'De Luxe Coupe' },
  { year: 1932, make: 'Ford', model: 'De Luxe Five-Window Coupe' },
  { year: 1973, make: 'Ford', model: 'Escort RS1600' },
  { year: 1977, make: 'Ford', model: 'Escort RS1800' },
  { year: 1992, make: 'Ford', model: 'Escort RS Cosworth' },
  { year: 1986, make: 'Ford', model: 'Escort RS Turbo' },
  { year: 1956, make: 'Ford', model: 'F-100' },
  { year: 2018, make: 'Ford', model: 'F-150 Prerunner DeBerti Design Truck' },
  { year: 2017, make: 'Ford', model: 'F-150 Raptor' },
  { year: 2011, make: 'Ford', model: 'F-150 SVT Raptor' },
  { year: 2015, make: 'Ford', model: 'Falcon GT F 351' },
  { year: 1972, make: 'Ford', model: 'Falcon XA GT-HO' },
  { year: 1972, make: 'Ford', model: 'Falcon XA GT-HO Forza Edition' },
  { year: 2014, make: 'Ford', model: 'Fiesta ST' },
  { year: 1981, make: 'Ford', model: 'Fiesta XR2' },
  { year: 2003, make: 'Ford', model: 'Focus RS' },
  { year: 2009, make: 'Ford', model: 'Focus RS' },
  { year: 2017, make: 'Ford', model: 'Focus RS' },
  { year: 2014, make: 'Ford', model: 'FPV Limited Edition Pursuit Ute' },
  { year: 2005, make: 'Ford', model: 'GT' },
  { year: 1964, make: 'Ford', model: 'GT40 Mk I' },
  { year: 1977, make: 'Ford', model: 'GT70' },
  { year: 1966, make: 'Ford', model: 'Lotus Cortina' },
  { year: 2017, make: 'Ford', model: 'M-Sport Fiesta RS' },
  { year: 1968, make: 'Ford', model: 'Mustang 2+2 Fastback' },
  { year: 1969, make: 'Ford', model: 'Mustang Boss 302' },
  { year: 2018, make: 'Ford', model: 'Mustang GT' },
  { year: 1965, make: 'Ford', model: 'Mustang GT Coupe' },
  { year: 2018, make: 'Ford', model: 'Mustang GT DeBerti Design' },
  { year: 1971, make: 'Ford', model: 'Mustang Mach 1' },
  { year: 2018, make: 'Ford', model: 'Mustang RTR Spec 5' },
  { year: 2020, make: 'Ford', model: 'Mustang Shelby GT500' },
  { year: 1981, make: 'Ford', model: 'Racing Puma' },
  { year: 2019, make: 'Ford', model: 'Ranger Raptor' },
  { year: 2014, make: 'Ford', model: 'Ranger T6 Rally Raid' },
  { year: 1932, make: 'Ford', model: 'Roadster "Hula Girl"' },
  { year: 2016, make: 'Ford', model: 'Shelby GT350R' },
  { year: 1987, make: 'Ford', model: 'Sierra Cosworth RS500' },
  { year: 1946, make: 'Ford', model: 'Super Deluxe Station Wagon' },
  { year: 1994, make: 'Ford', model: 'Supervan 3' },
  { year: 1993, make: 'Ford', model: 'SVT Cobra R' },
  { year: 2000, make: 'Ford', model: 'SVT Cobra R' },
  { year: 1965, make: 'Ford', model: 'Transit' },
  { year: 2011, make: 'Ford', model: 'Transit SuperSportVan' },
  { year: 2011, make: 'Ford', model: 'Transit SuperSportVan Forza Edition' },
  { year: 1973, make: 'Ford', model: 'XB Falcon GT' },
  { year: 1991, make: 'GMC', model: 'Syclone' },
  { year: 1992, make: 'GMC', model: 'Typhoon' },
  { year: 1983, make: 'GMC', model: 'Vandura G-1500' },
  { year: 1985, make: 'HDT', model: 'VK Commodore Group A' },
  { year: 1966, make: 'Hillman', model: 'Imp' },
  { year: 1973, make: 'Holden', model: 'HQ Monaro GTS 350' },
  { year: 1974, make: 'Holden', model: 'Sandman HQ Panelvan' },
  { year: 1977, make: 'Holden', model: 'Torana A9X' },
  { year: 1988, make: 'Holden', model: 'VL Commodore Group A SV' },
  { year: 2016, make: 'Honda', model: 'Civic Coupe GRC' },
  { year: 1984, make: 'Honda', model: 'Civic CRX Mugen' },
  { year: 1974, make: 'Honda', model: 'Civic RS' },
  { year: 2007, make: 'Honda', model: 'Civic Type-R' },
  { year: 2018, make: 'Honda', model: 'Civic Type R' },
  { year: 1991, make: 'Honda', model: 'CR-X SiR' },
  { year: 1992, make: 'Honda', model: 'NSX-R' },
  { year: 2005, make: 'Honda', model: 'NSX-R' },
  { year: 2005, make: 'Honda', model: 'NSX-R GT' },
  { year: 1994, make: 'Honda', model: 'Prelude Si' },
  { year: 2015, make: 'Honda', model: 'Ridgeline Baja Trophy Truck' },
  { year: 1970, make: 'Honda', model: 'S800' },
  { year: 2003, make: 'Honda', model: 'S2000' },
  { year: 2009, make: 'Honda', model: 'S2000 CR' },
  { year: 1955, make: 'Hoonigan', model: 'Chevrolet Bel Air' },
  { year: 1974, make: 'Hoonigan', model: 'Ford Bronco' },
  { year: 1978, make: 'Hoonigan', model: 'Ford Escort RS1800' },
  { year: 1986, make: 'Hoonigan', model: 'Ford RS200 Evolution' },
  { year: 2015, make: 'Hoonigan', model: 'Gymkhana 8 Ford Fiesta ST RX43' },
  { year: 2016, make: 'Hoonigan', model: 'Gymkhana 9 Ford Focus RS RX' },
  { year: 2016, make: 'Hoonigan', model: 'Gymkhana 9 Ford Focus RS RX \"Welcome Pack\"' },
  { year: 1991, make: 'Hoonigan', model: 'Gymkhana 10 Ford Escort Cosworth Group A' },
  { year: 1992, make: 'Hoonigan', model: 'Mazda RX-7 Twerkstallion' },
  { year: 1972, make: 'Hoonigan', model: 'Chevrolet \"Napalm Nova\"' },
  { year: 1991, make: 'Hoonigan', model: 'Rauh-Welt Begriff Porsche 911 Turbo' },
  { year: 2018, make: 'Hot Wheels', model: '2JetZ' },
  { year: 2011, make: 'Hot Wheels', model: 'Bone Shaker' },
  { year: 1972, make: 'Hot Wheels', model: 'Chevrolet LUV' },
  { year: 1949, make: 'Hot Wheels', model: 'Ford F-5 Dually Custom Hot Rod' },
  { year: 2005, make: 'Hot Wheels', model: 'Ford Mustang' },
  { year: 1969, make: 'Hot Wheels', model: 'International-Harvester Loadstar CO-1600' },
  { year: 1957, make: 'Hot Wheels', model: 'Nash Metropolitan Custom' },
  { year: 1957, make: 'Hot Wheels', model: 'Studebaker Golden Hawk "Dream Roadster"' },
  { year: 2014, make: 'HSV', model: 'Gen-F GTS' },
  { year: 2011, make: 'HSV', model: 'GTS' },
  { year: 1996, make: 'HSV', model: 'GTSR' },
  { year: 2016, make: 'HSV', model: 'Limited Edition Gen-F GTS Maloo' },
  { year: 1952, make: 'Hudson', model: 'Hornet' },
  { year: 2006, make: 'Hummer', model: 'H1 Alpha' },
  { year: 2006, make: 'Hummer', model: 'H1 Alpha Open Top' },
  { year: 2019, make: 'Hyundai', model: 'Veloster N' },
  { year: 2015, make: 'Infiniti', model: 'Q60 Concept' },
  { year: 1970, make: 'International', model: 'Scout 800A' },
  { year: 2018, make: 'Italdesign', model: 'Zerouno' },
  { year: 1953, make: 'Jaguar', model: 'C-Type' },
  { year: 1956, make: 'Jaguar', model: 'D-Type' },
  { year: 1961, make: 'Jaguar', model: 'E-type S1' },
  { year: 2017, make: 'Jaguar', model: 'F-Pace S' },
  { year: 2016, make: 'Jaguar', model: 'F-Type Project 7' },
  { year: 2015, make: 'Jaguar', model: 'F-Type R Coupe' },
  { year: 1964, make: 'Jaguar', model: 'Lightweight E-Type' },
  { year: 1959, make: 'Jaguar', model: 'Mk II 3.8' },
  { year: 2015, make: 'Jaguar', model: 'XFR-S' },
  { year: 1954, make: 'Jaguar', model: 'XK 120 SE' },
  { year: 2012, make: 'Jaguar', model: 'XKR-S' },
  { year: 2015, make: 'Jaguar', model: 'XKR-S GT' },
  { year: 1964, make: 'James Bond Edition', model: 'Aston-Martin DB5' },
  { year: 1969, make: 'James Bond Edition', model: 'Aston-Martin DBS' },
  { year: 2008, make: 'James Bond Edition', model: 'Aston-Martin DBS' },
  { year: 2015, make: 'James Bond Edition', model: 'Aston-Martin DB10' },
  { year: 1986, make: 'James Bond Edition', model: 'Aston-Martin V8' },
  { year: 1999, make: 'James Bond Edition', model: 'BMW Z8' },
  { year: 1981, make: 'James Bond Edition', model: 'Citroën 2CV6' },
  { year: 1977, make: 'James Bond Edition', model: 'Lotus Esprit S1' },
  { year: 1976, make: 'Jeep', model: 'CJ5 Renegade' },
  { year: 1976, make: 'Jeep', model: 'CJ5 Renegade \"Welcome Pack\"' },
  { year: 2020, make: 'Jeep', model: 'Gladiator Rubicon' },
  { year: 2014, make: 'Jeep', model: 'Grand Cherokee SRT' },
  { year: 2016, make: 'Jeep', model: 'Trailcat' },
  { year: 2012, make: 'Jeep', model: 'Wrangler Rubicon' },
  { year: 2018, make: 'Kia', model: 'Stinger' },
  { year: 2002, make: 'Koenigsegg', model: 'CC8S' },
  { year: 2008, make: 'Koenigsegg', model: 'CCGT' },
  { year: 2006, make: 'Koenigsegg', model: 'CCX' },
  { year: 2018, make: 'KTM', model: 'X-Bow GT4' },
  { year: 1956, make: 'KTM', model: 'X-Bow R' },
  { year: 2012, make: 'Lamborghini', model: 'Aventador J' },
  { year: 2012, make: 'Lamborghini', model: 'Aventador LP700-4' },
  { year: 2012, make: 'Lamborghini', model: 'Aventador LP700-4 Forza Edition' },
  { year: 1988, make: 'Lamborghini', model: 'Countach LP5000 QV' },
  { year: 1999, make: 'Lamborghini', model: 'Diablo GTR' },
  { year: 2011, make: 'Lamborghini', model: 'Gallardo LP570-4 Superleggera' },
  { year: 2012, make: 'Lamborghini', model: 'Gallardo LP570-4 Spyder Performante' },
  { year: 2014, make: 'Lamborghini', model: 'Huracán LP 610-4' },
  { year: 2018, make: 'Lamborghini', model: 'Huracán Performante' },
  { year: 1972, make: 'Lamborghini', model: 'Jarama S' },
  { year: 1986, make: 'Lamborghini', model: 'LM 002' },
  { year: 2010, make: 'Lamborghini', model: 'Murciélago LP 670-4 SV' },
  { year: 2008, make: 'Lamborghini', model: 'Reventón' },
  { year: 2008, make: 'Lamborghini', model: 'Reventón Forza Edition' },
  { year: 2019, make: 'Lamborghini', model: 'Urus' },
  { year: 1982, make: 'Lancia', model: '037 Stradale' },
  { year: 1992, make: 'Lancia', model: 'Delta HF Integrale Evo' },
  { year: 1986, make: 'Lancia', model: 'Delta S4' },
  { year: 1986, make: 'Lancia', model: 'Fulvia Coupé Rallye 1.6 HF' },
  { year: 1974, make: 'Lancia', model: 'Stratos HF Stradale' },
  { year: 1997, make: 'Land Rover', model: 'Defender 90' },
  { year: 1970, make: 'Land Rover', model: 'Range Rover' },
  { year: 2015, make: 'Land Rover', model: 'Range Rover Sport SVR' },
  { year: 2018, make: 'Land Rover', model: 'Range Rover Velar First Edition' },
  { year: 1972, make: 'Land Rover', model: 'Series III' },
  { year: 1972, make: 'Land Rover', model: 'Series III Forza Edition' },
  { year: 2010, make: 'Lexus', model: 'LFA' },
  { year: 2014, make: 'Local', model: 'Motors Rally Fighter' },
  { year: 2009, make: 'Lotus', model: '2-Eleven' },
  { year: 2016, make: 'Lotus', model: '3-Eleven' },
  { year: 2000, make: 'Lotus', model: '340R' },
  { year: 1971, make: 'Lotus', model: 'Elan Sprint' },
  { year: 1956, make: 'Lotus', model: 'Eleven' },
  { year: 2005, make: 'Lotus', model: 'Elise 111S' },
  { year: 1997, make: 'Lotus', model: 'Elise GT1' },
  { year: 1999, make: 'Lotus', model: 'Elise Series 1 Sport 190' },
  { year: 2002, make: 'Lotus', model: 'Esprit V8' },
  { year: 2011, make: 'Lotus', model: 'Evora S' },
  { year: 2012, make: 'Lotus', model: 'Exige S' },
  { year: 1957, make: 'Maserati', model: '300 S' },
  { year: 1953, make: 'Maserati', model: 'A6GCS/53 Pininfarina Berlinetta' },
  { year: 2010, make: 'Maserati', model: 'Gran Turismo S' },
  { year: 2014, make: 'Maserati', model: 'Ghibli S Q4' },
  { year: 2017, make: 'Maserati', model: 'Levante S' },
  { year: 2004, make: 'Maserati', model: 'MC12' },
  { year: 2004, make: 'Maserati', model: 'MC12 Forza Edition' },
  { year: 2008, make: 'Maserati', model: 'MC12 Versione Corsa' },
  { year: 1961, make: 'Maserati', model: 'Tipo 61 Birdcage' },
  { year: 1972, make: 'Mazda', model: 'Cosmo 110S Series II' },
  { year: 2005, make: 'Mazda', model: 'Mazdaspeed MX-5' },
  { year: 2013, make: 'Mazda', model: 'MX-5' },
  { year: 2016, make: 'Mazda', model: 'MX-5' },
  { year: 1994, make: 'Mazda', model: 'MX-5 Miata' },
  { year: 1973, make: 'Mazda', model: 'RX-3' },
  { year: 1997, make: 'Mazda', model: 'RX-7' },
  { year: 1985, make: 'Mazda', model: 'RX-7 GSL-SE' },
  { year: 2002, make: 'Mazda', model: 'RX-7 Spirit R Type-A' },
  { year: 2011, make: 'Mazda', model: 'RX-8 R3' },
  { year: 1990, make: 'Mazda', model: 'Savanna RX-7' },
  { year: 2011, make: 'McLaren', model: '12C Coupé' },
  { year: 2015, make: 'McLaren', model: '570S Coupé' },
  { year: 2018, make: 'McLaren', model: '600LT Coupé' },
  { year: 2018, make: 'McLaren', model: '720S Preorder Car' },
  { year: 2016, make: 'Mercedes AMG', model: 'C 63 S Coupé' },
  { year: 2018, make: 'Mercedes AMG', model: 'E 63 S' },
  { year: 2017, make: 'Mercedes AMG', model: 'GT R' },
  { year: 2015, make: 'Mercedes AMG', model: 'GT S' },
  { year: 2018, make: 'Mercedes AMG', model: 'GT 4-Door Coupé' },
  { year: 2015, make: 'Mercedes Benz', model: '#24 Tankpool24 Racing Truck' },
  { year: 1990, make: 'Mercedes Benz', model: '190E 2.5-16 Evolution II' },
  { year: 1967, make: 'Mercedes Benz', model: '280 SL' },
  { year: 1954, make: 'Mercedes Benz', model: '300 SL Coupé' },
  { year: 1955, make: 'Mercedes Benz', model: '300 SLR' },
  { year: 1998, make: 'Mercedes Benz', model: 'AMG CLK GTR' },
  { year: 2012, make: 'Mercedes Benz', model: 'C 63 AMG Coupé Black Series' },
  { year: 2013, make: 'Mercedes Benz', model: 'E 63 AMG' },
  { year: 2017, make: 'Mercedes Benz', model: 'E 350 D 4MATIC Terrain \"Project E-AT\"' },
  { year: 2014, make: 'Mercedes Benz', model: 'G 63 AMG 6x6' },
  { year: 2013, make: 'Mercedes Benz', model: 'G 65 AMG' },
  { year: 2011, make: 'Mercedes Benz', model: 'SLS AMG' },
  { year: 1929, make: 'Mercedes Benz', model: 'Super Sport Kurz Barker Roadster' },
  { year: 2014, make: 'Mercedes Benz', model: 'Unimog U5023' },
  { year: 2018, make: 'Mercedes Benz', model: 'X-Class' },
  { year: 1970, make: 'Mercury', model: 'Cougar Eliminator' },
  { year: 1949, make: 'Mercury', model: 'Coupe' },
  { year: 1971, make: 'Meyers', model: 'Manx' },
  { year: 1986, make: 'MG', model: 'Metro 6R4' },
  { year: 1958, make: 'MG', model: 'MGA Twin-Cam' },
  { year: 1966, make: 'MG', model: 'MGB GT' },
  { year: 1938, make: 'MG', model: 'TA Midget' },
  { year: 1965, make: 'MINI', model: 'Cooper S' },
  { year: 2009, make: 'MINI', model: 'John Cooper Works' },
  { year: 2018, make: 'MINI', model: 'John Cooper Works Convertible' },
  { year: 2012, make: 'MINI', model: 'John Cooper Works GP' },
  { year: 2014, make: 'MINI', model: 'X-Raid All4 Racing Countryman' },
  { year: 1995, make: 'Mitsubishi', model: 'Eclipse GSX' },
  { year: 1992, make: 'Mitsubishi', model: 'Galant VR-4' },
  { year: 1997, make: 'Mitsubishi', model: 'GTO' },
  { year: 1999, make: 'Mitsubishi', model: 'Lancer Evolution VI GSR' },
  { year: 2004, make: 'Mitsubishi', model: 'Lancer Evolution VIII MR' },
  { year: 2006, make: 'Mitsubishi', model: 'Lancer Evolution IX MR' },
  { year: 2008, make: 'Mitsubishi', model: 'Lancer Evolution X GSR' },
  { year: 1988, make: 'Mitsubishi', model: 'Starion ESI-R' },
  { year: 2014, make: 'Morgan', model: '3 Wheeler' },
  { year: 2018, make: 'Morgan', model: 'Aero GT' },
  { year: 2010, make: 'Morgan', model: 'Aero Supersports' },
  { year: 1958, make: 'Morris', model: 'Minor 1000' },
  { year: 2010, make: 'Mosler', model: 'MT900S' },
  { year: 1993, make: 'Nissan', model: '240SX SE' },
  { year: 2010, make: 'Nissan', model: '370Z' },
  { year: 2003, make: 'Nissan', model: 'Fairlady Z' },
  { year: 1969, make: 'Nissan', model: 'Fairlady Z 432' },
  { year: 1994, make: 'Nissan', model: 'Fairlady Z Version S Twin Turbo' },
  { year: 1995, make: 'Nissan', model: 'Nismo GT-R LM' },
  { year: 1995, make: 'Nissan', model: 'Nismo GT-R LM Forza Edition' },
  { year: 1991, make: 'Nissan', model: 'Pulsar GTI-R' },
  { year: 1993, make: 'Nissan', model: 'Pulsar GTI-R' },
  { year: 1998, make: 'Nissan', model: 'R390' },
  { year: 2018, make: 'Nissan', model: 'Sentra Nismo' },
  { year: 1992, make: 'Nissan', model: 'Silvia Club K\'s' },
  { year: 1994, make: 'Nissan', model: 'Silvia K\'s' },
  { year: 1998, make: 'Nissan', model: 'Silvia K\'s Aero' },
  { year: 2000, make: 'Nissan', model: 'Silvia Spec-R' },
  { year: 1971, make: 'Nissan', model: 'Skyline 2000GT-R' },
  { year: 1993, make: 'Nissan', model: 'Skyline GT-R V-Spec' },
  { year: 1997, make: 'Nissan', model: 'Skyline GT-R V-Spec' },
  { year: 2002, make: 'Nissan', model: 'Skyline GT-R V-Spec II' },
  { year: 1987, make: 'Nissan', model: 'Skyline GTS-R (R31)' },
  { year: 1973, make: 'Nissan', model: 'Skyline H/T 2000GT-R' },
  { year: 2016, make: 'Nissan', model: 'Titan Warrior Concept' },
  { year: 1969, make: 'Oldsmobile', model: 'Hurst/Olds 442' },
  { year: 1963, make: 'Opel', model: 'Kadett A' },
  { year: 1984, make: 'Opel', model: 'Manta 400' },
  { year: 2010, make: 'Pagani', model: 'Zonda R' },
  { year: 1962, make: 'Peel', model: 'P50' },
  { year: 1965, make: 'Peel', model: 'Trident' },
  { year: 1991, make: 'Peugeot', model: '205 Rallye' },
  { year: 1984, make: 'Peugeot', model: '205 Turbo 16' },
  { year: 1984, make: 'Peugeot', model: '205 Turbo 16 Forza Edition' },
  { year: 2007, make: 'Peugeot', model: '207 Super 2000' },
  { year: 1959, make: 'Plymouth', model: 'Atomic Punk Bubbletop' },
  { year: 1971, make: 'Plymouth', model: 'Cuda 426 Hemi' },
  { year: 1958, make: 'Plymouth', model: 'Fury' },
  { year: 1970, make: 'Plymouth', model: 'Hemi Cuda Convertible Barrett-Jackson Edition' },
  { year: 2015, make: 'Polaris', model: 'RZR XP 1000 EPS' },
  { year: 1968, make: 'Pontiac', model: 'Firebird' },
  { year: 1977, make: 'Pontiac', model: 'Firebird Trans Am' },
  { year: 1987, make: 'Pontiac', model: 'Firebird Trans Am GTA' },
  { year: 1973, make: 'Pontiac', model: 'Firebird Trans Am SD-455' },
  { year: 1965, make: 'Pontiac', model: 'GTO' },
  { year: 1969, make: 'Pontiac', model: 'GTO Judge' },
  { year: 1971, make: 'Porsche', model: '#3 917 LH' },
  { year: 1971, make: 'Porsche', model: '#23 917/20' },
  { year: 1951, make: 'Porsche', model: '#46 356 SL Gmünd Coupe' },
  { year: 1986, make: 'Porsche', model: '#185 959 Prodrive Rally Raid' },
  { year: 1959, make: 'Porsche', model: '356 A 1600 Super' },
  { year: 1957, make: 'Porsche', model: '356A Speedster' },
  { year: 1960, make: 'Porsche', model: '356 RSR from Emory Motorsport' },
  { year: 1964, make: 'Porsche', model: '356 C Cabriolet Emory Special' },
  { year: 1956, make: 'Porsche', model: '550 Spyder' },
  { year: 2018, make: 'Porsche', model: '718 Cayman GTS' },
  { year: 1960, make: 'Porsche', model: '718 RS 60' },
  { year: 1960, make: 'Porsche', model: '718 RS 60 \"Welcome Pack\"' },
  { year: 1966, make: 'Porsche', model: '906 Carrera 6' },
  { year: 1995, make: 'Porsche', model: '911 Carrera 2 by Gunther Werks' },
  { year: 1973, make: 'Porsche', model: '911 Carrera RS' },
  { year: 2019, make: 'Porsche', model: '911 Carrera S' },
  { year: 1995, make: 'Porsche', model: '911 GT2' },
  { year: 2004, make: 'Porsche', model: '911 GT3' },
  { year: 2018, make: 'Porsche', model: '911 GT2 RS' },
  { year: 2019, make: 'Porsche', model: '911 GT3 RS' },
  { year: 2016, make: 'Porsche', model: '911 GT3 RS Preorder Car' },
  { year: 1982, make: 'Porsche', model: '911 Turbo 3.3' },
  { year: 1970, make: 'Porsche', model: '914/6' },
  { year: 1993, make: 'Porsche', model: '928 GTS' },
  { year: 1989, make: 'Porsche', model: '944 Turbo' },
  { year: 1987, make: 'Porsche', model: '959' },
  { year: 1993, make: 'Porsche', model: '968 Turbo S' },
  { year: 2003, make: 'Porsche', model: 'Carrera GT' },
  { year: 2012, make: 'Porsche', model: 'Cayenne Turbo' },
  { year: 2018, make: 'Porsche', model: 'Cayenne Turbo' },
  { year: 2016, make: 'Porsche', model: 'Cayman GT4' },
  { year: 2015, make: 'Porsche', model: 'Cayman GTS' },
  { year: 2015, make: 'Porsche', model: 'Macan Turbo' },
  { year: 2019, make: 'Porsche', model: 'Macan Turbo' },
  { year: 2017, make: 'Porsche', model: 'Panamera Turbo' },
  { year: 723, make: 'Quartz', model: 'Regalia' },
  { year: 723, make: 'Quartz', model: 'Regalia Type-D' },
  { year: 2015, make: 'Radical', model: 'RXC Turbo' },
  { year: 2013, make: 'Ram', model: '2500 Power Wagon' },
  { year: 1972, make: 'Reliant', model: 'Supervan III' },
  { year: 1980, make: 'Renault', model: '5 Turbo' },
  { year: 1980, make: 'Renault', model: '5 Turbo Forza Edition' },
  { year: 1973, make: 'Renault', model: 'Alpine A110 1600S' },
  { year: 2010, make: 'Renault', model: 'Clio R.S.' },
  { year: 2016, make: 'Renault', model: 'Clio R.S. 16 Concept' },
  { year: 2010, make: 'Renault', model: 'Clio R.S. Forza Edition' },
  { year: 2013, make: 'Renault', model: 'Clio R.S. 200 EDC' },
  { year: 2007, make: 'Renault', model: 'Clio RS 197' },
  { year: 1993, make: 'Renault', model: 'Clio Williams' },
  { year: 2018, make: 'Renault', model: 'Megane R.S.' },
  { year: 2010, make: 'Renault', model: 'Megane RS 250' },
  { year: 2008, make: 'Renault', model: 'Mégane R26.R' },
  { year: 2003, make: 'Renault', model: 'Sport Clio V6' },
  { year: 2010, make: 'Rossion', model: 'Q1' },
  { year: 1984, make: 'Rover', model: 'SD1 Vitesse' },
  { year: 2010, make: 'Saleen', model: 'S5S Raptor' },
  { year: 2004, make: 'Saleen', model: 'S7' },
  { year: 2012, make: 'Shelby', model: '1000' },
  { year: 1965, make: 'Shelby', model: 'Cobra 427 S/C' },
  { year: 1965, make: 'Shelby', model: 'Cobra Daytona Coupe' },
  { year: 1963, make: 'Shelby', model: 'Monaco King Cobra' },
  { year: 2016, make: 'Subaru', model: '#199 WRX STI VT15R Rally Car' },
  { year: 2016, make: 'Subaru', model: '#199 WRX STI VT15R Rally Car \"Welcome Pack\"' },
  { year: 2013, make: 'Subaru', model: 'BRZ' },
  { year: 1998, make: 'Subaru', model: 'Impreza 22B STi' },
  { year: 2004, make: 'Subaru', model: 'Impreza WRX STI' },
  { year: 2005, make: 'Subaru', model: 'Impreza WRX STI' },
  { year: 2008, make: 'Subaru', model: 'Impreza WRX STI' },
  { year: 1990, make: 'Subaru', model: 'Legacy RS' },
  { year: 2011, make: 'Subaru', model: 'WRX STI' },
  { year: 2015, make: 'Subaru', model: 'WRX STI' },
  { year: 1967, make: 'Sunbeam', model: 'Tiger' },
  { year: 1979, make: 'Talbot', model: 'Sunbeam Lotus' },
  { year: 2017, make: 'Tamo', model: 'Racemo' },
  { year: 2014, make: 'Terradyne', model: 'Gurkha LAPV' },
  { year: 2018, make: 'Top', model: 'Gear Track-Tor' },
  { year: 1993, make: 'Toyota', model: '#1 T100 Baja Truck' },
  { year: 1993, make: 'Toyota', model: '#1 T100 Baja Truck \"Welcome Pack\"' },
  { year: 1969, make: 'Toyota', model: '2000GT' },
  { year: 1974, make: 'Toyota', model: 'Celica GT' },
  { year: 1992, make: 'Toyota', model: 'Celica GT-Four RC ST185' },
  { year: 1994, make: 'Toyota', model: 'Celica GT-Four ST205' },
  { year: 1974, make: 'Toyota', model: 'Corolla SR5' },
  { year: 2013, make: 'Toyota', model: 'GT86' },
  { year: 2007, make: 'Toyota', model: 'Hilux Arctic Trucks AT38' },
  { year: 2016, make: 'Toyota', model: 'Land Cruiser Arctic Trucks AT37' },
  { year: 1995, make: 'Toyota', model: 'MR2 GT' },
  { year: 1989, make: 'Toyota', model: 'MR2 SC' },
  { year: 1985, make: 'Toyota', model: 'Sprinter Trueno GT Apex' },
  { year: 1992, make: 'Toyota', model: 'Supra 2.0 GT Twin Turbo' },
  { year: 1998, make: 'Toyota', model: 'Supra RZ' },
  { year: 1962, make: 'Triumph', model: 'Spitfire' },
  { year: 1962, make: 'Triumph', model: 'TR3B' },
  { year: 1970, make: 'Triumph', model: 'TR6 PI' },
  { year: 1979, make: 'Triumph', model: 'TR7 Roadster' },
  { year: 1998, make: 'TVR', model: 'Cerbera Speed 12' },
  { year: 2005, make: 'TVR', model: 'Sagaris' },
  { year: 2005, make: 'TVR', model: 'Sagaris Forza Edition' },
  { year: 2001, make: 'TVR', model: 'Tuscan S' },
  { year: 2018, make: 'TVR', model: 'Griffith' },
  { year: 2012, make: 'Vauxhall', model: 'Astra VXR' },
  { year: 2009, make: 'Vauxhall', model: 'Corsa VXR' },
  { year: 2016, make: 'Vauxhall', model: 'Corsa VXR' },
  { year: 2010, make: 'Vauxhall', model: 'Insignia VXR' },
  { year: 2005, make: 'Vauxhall', model: 'Monaro VXR' },
  { year: 1990, make: 'Vauxhall', model: 'Lotus Carlton' },
  { year: 2004, make: 'Vauxhall', model: 'VX220 Turbo' },
  { year: 2017, make: 'Volkswagen', model: '#34 Volkswagen Andretti Rallycross Beetle' },
  { year: 1970, make: 'Volkswagen', model: '#1107 Desert Dingo Racing Stock Bug' },
  { year: 1963, make: 'Volkswagen', model: 'Beetle' },
  { year: 1963, make: 'Volkswagen', model: 'Class 5/1600 Baja Bug' },
  { year: 1995, make: 'Volkswagen', model: 'Corrado VR6' },
  { year: 1966, make: 'Volkswagen', model: 'Double Cab Pick-Up' },
  { year: 2014, make: 'Volkswagen', model: 'Global RallyCross Beetle' },
  { year: 1983, make: 'Volkswagen', model: 'Golf GTI' },
  { year: 1992, make: 'Volkswagen', model: 'Golf Gti 16v Mk2' },
  { year: 2014, make: 'Volkswagen', model: 'Golf R' },
  { year: 2003, make: 'Volkswagen', model: 'Golf R32' },
  { year: 1998, make: 'Volkswagen', model: 'GTI VR6 Mk3' },
  { year: 2011, make: 'Volkswagen', model: 'Scirocco R' },
  { year: 1981, make: 'Volkswagen', model: 'Scirocco S' },
  { year: 2008, make: 'Volkswagen', model: 'Touareg R50' },
  { year: 1962, make: 'Volkswagen', model: 'Type 2 De Luxe' },
  { year: 1962, make: 'Volkswagen', model: 'Type 2 De Luxe Forza Edition' },
  { year: 1983, make: 'Volvo', model: '242 Turbo Evolution' },
  { year: 1963, make: 'Volvo', model: '850 R' },
  { year: 2015, make: 'Volvo', model: 'V60 Polestar' },
  { year: 2016, make: 'W Motors', model: 'Lykan HyperSport' },
  { year: 1945, make: 'Willys', model: 'MB Jeep' },
];

const byMake: Record<string, CarModel[]> = makes.reduce((acc, make) => ({
  ...acc,
  [make]: [],
}), {});

models.forEach((model) => {
  byMake[model.make].push({
    ...model,
    fullname: `${model.year} ${model.make} ${model.model}`,
    shortname: `${model.year} ${model.model}`,
  });
});

export default byMake;
